### ISSUE TITLE
Compiler crash if number used as function name

### ISSUE THREAD

**Issue by richq** [tdenniston/bish#19]
Here's a messed up bit of code that causes bish to segfault:

```
def f(n) {
    return 8(n);
}
```

An "invalid token type for atom" or similar error would be OK, I don't expect the code to actually work since numbers are used for argument passing in the compiled shell code.

**Comment by egorsmkv** [comment]
I might add that use "_" character in variable and function names can not. This is not very convenient.

**Comment by richq** [comment]
Yeah, but bish just doesn't like the _ and tells you so "Unhandled token character at character '_', line 4". That seems like a different issue to me "let me use _ in variable and function names".

**Comment by digitalsurgeon** [comment]
in the case of:

```
def f(n) {
return 8(n);
}
```

the problem lies in Parser.cpp Parser::factor()

```
 IRNode *a = atom(); // a is created as integer.
        if (tokenizer->peek().isa(Token::LParenType)) {
            Variable *v = static_cast<Variable*>(a); // casting it to Variable, Name is not initialized!!
            // The symbol will be reinserted as a Function, not a Variable.
            remove_from_symbol_table(v->name);
            a = funcall(v->name); // !!! CRASH IN FUNCALL
        }
```

The checker pass has not run at this point and the types are all undefined.

**Comment by tdenniston** [comment]
@richq can you verify that it's fixed? I actually wasn't seeing a segfault on my system.

@digitalsurgeon thanks very much for tracking that down. Made fixing it trivial :-).

**Comment by tdenniston** [comment]
@eg0r With commit 9214bce underscores are now allowed.

**Comment by egorsmkv** [comment]
@tdenniston Thanks!

**Comment by richq** [comment]
Confirmed, no longer crashes.
