### ISSUE TITLE
Is there a user's document?

### ISSUE THREAD

**Issue by oldfartdeveloper** [tdenniston/bish#2]
This looks very interesting to me; I share the author's frustration w/ `bash`.

That being said, the syntax looks very much like **C**.  I'm just wondering if there's a document on how to use this.

If not, w/ a little help from the author, I'd be glad to throw something together as a GitHub wiki page just to get people started.

Thanks for doing this!

**Comment by ryanmjacobs** [comment]
Yes, an `examples/` directory would be very nice.

Cool project, btw :grinning:

**Comment by gabesullice** [comment]
+1

**Comment by tdenniston** [comment]
Great idea, as there are currently no examples or FAQ or anything of the sort. The syntax is still in flux, but there should probably be at least a short introduction to bish.

**Comment by NeverI** [comment]
+1

**Comment by tdenniston** [comment]
I started a wiki page here: https://github.com/tdenniston/bish/.
