### ISSUE TITLE
Call the standard commands

### ISSUE THREAD

**Issue by egorsmkv** [tdenniston/bish#23]
For example, the following code will not be translated:

``` bash
var = "335f";
@($var =~ ^-?[0-9]+$);
```

Will be displayed parse error:
`Parsing error: Expected variable to be a symbol near character ')', line 5`

How best to do these teams? Maybe they wrap in quotes **`**?

**Comment by tdenniston** [comment]
Hmm. I'll have to figure out a good way to handle that. After the regex line-end symbol '$', bish expects there to be a variable name. That's because interpolations in strings are currently handled by prefixing '$' as well. I will need to think on this one a bit.

**Comment by egorsmkv** [comment]
Yes, I also realized that there must be a variable.

Ok, I'll wait.

**Comment by egorsmkv** [comment]
@tdenniston Why not use these quotes **`**?

**Comment by tdenniston** [comment]
@eg0r This should work now, for example:

```
text = "335";
@([[ $text =~ ^[0-9]+\$ ]]);
assert(success());
```

Seems to work as expected.

**Comment by egorsmkv** [comment]
Wonderful commit. Now you can make functions for type checking:

``` bash
def is_integer(v) {
    @([[ $v =~ ^[0-9]+\$ ]]);
    return success();
}

if (is_integer("100")) {
    println("Yes!");
} else {
    println("No!");
}

# => "Yes!"
```
