### ISSUE TITLE
Add "break / continue" as built-in operators

### ISSUE THREAD

**Issue by egorsmkv** [tdenniston/bish#33]
Each time not to cause this:

``` bash
start = 100;
end = 150;

for (i in start .. end) {
    if (i == 120) {
        @(continue); # or @(break)
    }

    println(i);
}
```

Thus it is necessary to expand the built-in operators to be available more simple expressions.

**Comment by egorsmkv** [comment]
@tdenniston 

Thanks.

It will be difficult to add these statements: **-=., +=, *=, /=, %=, and, not, or**? It is important to add arrays.

**Comment by tdenniston** [comment]
I plan to add those operators to the language. I also plan to add arrays to the language so that one doesn't have to use @(...) for array support. But those should be separate issues: I'll close this one now.

**Comment by egorsmkv** [comment]
@tdenniston I have a question.

If the language is similar to C, then it is probably better to make statements like there? Instead of "and, or" make "&&, ||".

**Comment by tdenniston** [comment]
Well, apart from curly braces and semicolons, similarity to C was never part of the design plan. In fact, I am shooting for more Pythonic syntax (apart from whitespace sensitivity, thus the braces and semicolons). Thus, 'and' and 'or' were deliberate choices. If there exists significant opposition to this decision, it will be easy to change.

**Comment by egorsmkv** [comment]
@tdenniston Got It. I, too, for the Python-style language.
