### ISSUE TITLE
Escape $ character

### ISSUE THREAD

**Issue by heyvito** [tdenniston/bish#36]
Is there any way to do it? I'm struggling to use `awk` in my bish script.
Already tried the following combinations:
- `@(awk "{ print $1 }");`
- `@(awk "{ print $$1 }");`
- `@(awk "{ print \$1 }");`

The result is the same, no matter the combination:

```
Parsing error: Expected variable to be a symbol near character '1', line 2
```

**Comment by egorsmkv** [comment]
The dollar is used to declare variables, so getting the error. You need to come up with another scheme for writing call arbitrary commands.

Author library already knows about it.

**Comment by heyvito** [comment]
Oh mate, I'm sorry. I didn't know he knew about it.
He may close this issue if he want.

Thank you!

**Comment by egorsmkv** [comment]
@victorgama Nothing to apologize for.

Language is only now developing. While sending a manual sooner :)

**Comment by tdenniston** [comment]
Hey, thanks for opening the issue. Now that I know multiple people are getting stuck on this issue, I'll make it higher priority. I just need to figure out a clean way to fix it.

**Comment by egorsmkv** [comment]
@tdenniston Any thoughts already have?

**Comment by heyvito** [comment]
@tdenniston Don't mention it! (:
I would love to help, but I don't have any C/C++ background.

**Comment by tdenniston** [comment]
@victorgama Can you verify that your issue is fixed? I added a test with the awk example, but I prefer to have you confirm it's fixed before I close it. I decided on the `\$` syntax to escape dollar signs.

**Comment by heyvito** [comment]
@tdenniston Works perfectly! Thank you!
