### ISSUE TITLE
Function arguments in interpolated strings don't work

### ISSUE THREAD

**Issue by tdenniston** [tdenniston/bish#42]
Test case:

```
def f(x) {
   println("x is: $x");
}
f("hello");
```

The argument $x does not get renamed to $1 during code generation:

```
function bish_f () {
    bish_println "x is: $x";
}
```

**Comment by egorsmkv** [comment]
You can do like [Batsh](http://batsh.org).

``` sh
function f(x) {
   print("x is: $x");
}
f("hello");
```

``` sh
function f {
  local x
  x="$1"
  "echo" "-ne" "x is: $x"
}
"f" "hello"
```

**Comment by tdenniston** [comment]
Hmm, that's a good idea. I might go with that. It would simplify code generation a bit.

**Comment by egorsmkv** [comment]
@tdenniston From the project, you can still take the idea of unlimited quantities has argument for the function "print".

**Comment by tdenniston** [comment]
Supporting variadic functions (functions with arbitrary numbers of arguments) is definitely planned. So much to implement, so little time!

**Comment by egorsmkv** [comment]
@tdenniston I think a lot of desires :smile:
