### ISSUE TITLE
Documentation translation

### ISSUE THREAD

**Issue by egorsmkv** [tdenniston/bish#46]
@tdenniston I can translate the documentation into Russian. Create a new page on the Wiki I did not get.

I think you need to create a folder in the repository and load transfers to her?

**Comment by tdenniston** [comment]
@eg0r You're a contributor, so you should be able to create a new wiki page. Is there a "new page" button? Did you get an error message?

**Comment by egorsmkv** [comment]
The button is there, but when you click on this address: https://github.com/tdenniston/bish/wiki/_new throws the main wiki.

**Comment by tdenniston** [comment]
I created a page for you to edit: https://github.com/tdenniston/bish/wiki/Home-(RUS). I don't know why you can't create pages yourself. Have at it, but could you please try to keep it as close as possible to the English version? Formatting, etc.

**Comment by egorsmkv** [comment]
I do not know what the problem is, but I can not make any changes.

Tried through cloning wiki, also comes out.

```
egor@book:~/Tests/Bish/t/bish.wiki > git push
Username for 'https://github.com': eg0r
Password for 'https://eg0r@github.com': 
remote: Permission to tdenniston/bish.wiki.git denied to eg0r.
fatal: unable to access 'https://github.com/tdenniston/bish.wiki.git/': The requested URL returned error: 403
```

**Comment by tdenniston** [comment]
Try it now. I had accidentally set wiki editing to private.

**Comment by egorsmkv** [comment]
Now there is no problem :smile:
