### ISSUE TITLE
"bish_success: command not found" when using exists()

### ISSUE THREAD

**Issue by richq** [tdenniston/bish#5]
Seems like when functions from StdLib are pulled in, the pulling in isn't recursive. Maybe just include the lot, regardless of if they are used or not? Bloat for the win!

The following example:

```
if (exists("file-that-does-not-exist")) {
    print("file exists");
}
```

gives this, which is missing bish_success function.

```
function bish_main () {
    if [[ $(bish_exists "file-that-does-not-exist") ]]; then
        bish_print "file exists";
    fi;
}

function bish_exists () {
    test -e $1;
    echo $(bish_success); exit;
}

function bish_print () {
    echo $1;
}

bish_main;
```

**Comment by tdenniston** [comment]
Hmm... I need to fix the `link_stdlib` function for this. I probably broke this with c3f0169.

**Comment by tdenniston** [comment]
Fixed with commit 036eabd.

**Comment by tdenniston** [comment]
By the way, the shorthand syntax for using function calls as booleans/values does not work yet. This:

```
if (func()) {
    do_something();
}
```

Should be implemented like this:

```
if (func() == true) {
    do_something();
}
```

Don't worry, it's on my to do list!

**Comment by richq** [comment]
OK, got it. Thanks.
