### ISSUE TITLE
Add support for arrays

### ISSUE THREAD

**Issue by tdenniston** [tdenniston/bish#53]
Bish should support simple array types.

**Comment by heyvito** [comment]
That would be really nice! Specially combined with `split` and `join`, if you intend to implement those.

**Comment by tdenniston** [comment]
@victorgama Adding split and join is a good idea: I'll hopefully get to that soon!

Closing this, as the `arrays.bish` test is passing. Report any array-related bugs in a separate issue.

**Comment by tdenniston** [comment]
Reopening: we should be able to pass arrays as function arguments. This is needed to implement an array length function in stdlib, for example.

**Comment by tdenniston** [comment]
Closing again. There is now a passing test for using arrays as arguments.
