### ISSUE TITLE
Version tagging

### ISSUE THREAD

**Issue by heyvito** [tdenniston/bish#54]
It would be nice if you could push a tag now and then, so I could write a Homebrew package! :sunglasses:

**Comment by tdenniston** [comment]
@victorgama I wanted to get bish a little more stable before I created a tag. My plan is to create the first tag when milestone 0.1 is reached, which shouldn't take too much additional work. Hopefully by the end of the weekend I can be confident enough in the stability/usability to create a 0.1 tag. I also want to create a few common distribution packages at the 0.1 milestone (e.g. for Ubuntu).

**Comment by heyvito** [comment]
Perfect! Let me know and then we publish it on brew ASAP. :D

**Comment by tdenniston** [comment]
Ok, after much delay, I've pushed a 0.1 tag! So I'll close this issue for now.

**Comment by heyvito** [comment]
Perfect! I will work on a brew package asap! (:

(Unless you want to do it by yourself)

-- 
Victor Gama
http://vito.io
+55 11 953 804 895

On April 20, 2015 at 12:59:19 PM, Tyler Denniston (notifications@github.com) wrote:

Closed #54.

**Comment by tdenniston** [comment]
Go for it!
