### ISSUE TITLE
Iteration of the array elements

### ISSUE THREAD

**Issue by egorsmkv** [tdenniston/bish#59]
I wrote the following script:

``` sh
a = [1, 2, 3, 4];

for (u in a) {
  println(u);
}
```

And got a bash script:

``` sh
# ...
function main () {
    for u in $a; do
        local _0="$u";
        StdLib_println "$_0";
    done;
}

function StdLib_println () {
    local s="$1";
    echo -e "$s";
}

a=( 1 2 3 4 );
main;
```

But when you start getting only the first element.

**Comment by tdenniston** [comment]
Ah, ok. I think I know what the problem is there. Thanks for reporting. It should be simple to fix.

**Comment by tdenniston** [comment]
@eg0r Can you verify that it's fixed for you now?

**Comment by egorsmkv** [comment]
@tdenniston Checked, there is no problem now.

And now the question is: the number of semicolons are not supported yet?

``` sh
a = [1.1, 1.2, 1.3];
```

**Comment by egorsmkv** [comment]
@tdenniston By the way, why not remove `()` next to the names of functions? Or is it important for some versions of bash?

**Comment by tdenniston** [comment]
@eg0r Floating point numbers (numbers with decimal points) are not supported yet. That's a limitation of bash. I have to figure out what to do about that. And, I should remove `()` next to functions. I thought they were necessary, but I was wrong.
