### ISSUE TITLE
Mathematical functions

### ISSUE THREAD

**Issue by egorsmkv** [tdenniston/bish#61]
Hi, @tdenniston 

I have created just such a library: https://gist.github.com/eg0r/4da3b0d75cabcbe29e1f

PR did not do, as it is necessary to formalize the library. I propose to move it to a separate folder and there are going to bish-files to be imported one, for example, `stdlib.bish`.

**Yeah, well, I ask to comment on my code, it can be somehow need to improve?**

**Comment by tdenniston** [comment]
@eg0r Thanks, this is great!

Your code looks good. I will create a separate folder for libraries and move `stdlib.bish` there. After that, you can create a PR with this library.

One question: is `bc` available on all systems? Do you know of any systems without `bc`?

**Comment by egorsmkv** [comment]
@tdenniston As suggested by [Wikipedia](http://en.wikipedia.org/wiki/Bc_%28programming_language%29) must be in UNIX. But it is possible to check in functions that will display abort.

**Comment by egorsmkv** [comment]
@tdenniston By the way, floating point numbers, you can do so.

``` sh
def float(x) {
  cmd = "scale=3; $x/1.0";
  return @(echo $cmd | bc);
}

println(float("43")); # => 43.000
```

**Comment by tdenniston** [comment]
@eg0r You can submit a PR for this library now.

**Comment by sandeep06011991** [comment]
Sorry to intrude ,
I am a programmer without university education trying to teach myself compilers by working on open source projects . I would really appreciate if you could give me simple tasks , some guidance ,anything at all . All help appreciated

**Comment by egorsmkv** [comment]
@sandeep06011991 Notes? Clone project and experiment!
